# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aab04ce0741e0e404bbf14211734463754c04993eb321eeb7fafdb6d0f07e73b532106e4b087eb482014955907eb7567a356087c3eaaefff15c94fd5019edf09

test:
  secret_key_base: 2d5605a96c04a194559836c64d49663648e6a844911ced2d1d8373d9c4789db5e3839557780091f395bbd39ce3c6ca7d8604d0dad15f9b015cd641d4db7ec622

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
